[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "HmgaDncYyDqmwT7axPykK9Gy5QFNB9pX3BBoNtwv3qjj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/arihantbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello Anchor'"